"""remove features and channel_count from package

Revision ID: 02b10157f8ac
Revises: fb933c0c9cfe
Create Date: 2025-12-26 00:12:09.002427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b10157f8ac'
down_revision: Union[str, Sequence[str], None] = 'fb933c0c9cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'channel_count')
    op.drop_column('package', 'features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('features', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('package', sa.Column('channel_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
