"""Rename staff role to agent

Revision ID: 0515a331f4f4
Revises: a753be398acd
Create Date: 2025-12-14 20:16:51.599913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0515a331f4f4'
down_revision: Union[str, Sequence[str], None] = 'a753be398acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename enum value: staff -> agent
    op.execute(
        "ALTER TYPE userrole RENAME VALUE 'STAFF' TO 'AGENT';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert enum value: agent -> staff
    op.execute(
        "ALTER TYPE userrole RENAME VALUE 'AGENT' TO 'STAFF';"
    )
    # ### end Alembic commands ###
