"""fix ftth_8 nullable

Revision ID: 1a07173e5327
Revises: 8da9b2fca738
Create Date: 2026-04-02 18:55:47.394789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a07173e5327'
down_revision: Union[str, Sequence[str], None] = '8da9b2fca738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'ftth_8',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('deviceinfo', 'account_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('deviceinfo', 'stb_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('deviceinfo', 'stb_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('deviceinfo', 'account_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customer', 'ftth_8',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
