"""add numeric price to package, add name constraints to tvtype

Revision ID: 24c43c6c943b
Revises: 97d11a5519ad
Create Date: 2026-04-28 21:40:46.369323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24c43c6c943b'
down_revision: Union[str, Sequence[str], None] = '97d11a5519ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_ftth64_name'), table_name='ftth64')
    op.create_unique_constraint('uq_ftth64_name', 'ftth64', ['name'])
    op.alter_column('package', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.drop_index(op.f('ix_package_price'), table_name='package')
    op.create_unique_constraint("uq_package_name", 'package', ['name'])
    op.drop_index(op.f('ix_tvtype_name'), table_name='tvtype')
    op.create_unique_constraint("uq_tvtype_name", 'tvtype', ['name'])
    op.alter_column('village', 'village_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_village_name'), table_name='village')
    op.drop_index(op.f('ix_village_village_code'), table_name='village')
    op.create_unique_constraint('uq_village_village_code', 'village', ['village_code'])
    op.create_unique_constraint('uq_village_name', 'village', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_village_name', 'village', type_='unique')
    op.drop_constraint('uq_village_village_code', 'village', type_='unique')
    op.create_index(op.f('ix_village_village_code'), 'village', ['village_code'], unique=True)
    op.create_index(op.f('ix_village_name'), 'village', ['name'], unique=True)
    op.alter_column('village', 'village_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint("uq_tvtype_name", 'tvtype', type_='unique')
    op.create_index(op.f('ix_tvtype_name'), 'tvtype', ['name'], unique=False)
    op.drop_constraint("uq_package_name", 'package', type_='unique')
    op.create_index(op.f('ix_package_price'), 'package', ['price'], unique=False)
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=True)
    op.alter_column('package', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint('uq_ftth64_name', 'ftth64', type_='unique')
    op.create_index(op.f('ix_ftth64_name'), 'ftth64', ['name'], unique=False)
    op.alter_column('customer', 'phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
