"""Increase code field lengths to 30

Revision ID: 2b5ec4adb5cc
Revises: e62b15b3415e
Create Date: 2025-12-20 12:13:29.985973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5ec4adb5cc'
down_revision: Union[str, Sequence[str], None] = 'e62b15b3415e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'village',
        'village_code',
        existing_type=sa.VARCHAR(length=10),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False
    )

    op.alter_column(
        'bill',
        'bill_code',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False
    )

    op.alter_column(
        'deviceinfo',
        'account_number',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False
    )

    op.alter_column(
        'deviceinfo',
        'vc_number',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False
    )

    op.alter_column(
        'deviceinfo',
        'previous_vc_number',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'deviceinfo',
        'previous_vc_number',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True
    )

    op.alter_column(
        'deviceinfo',
        'vc_number',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False
    )

    op.alter_column(
        'deviceinfo',
        'account_number',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False
    )

    op.alter_column(
        'bill',
        'bill_code',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False
    )

    op.alter_column(
        'village',
        'village_code',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False
    )
    # ### end Alembic commands ###
