"""add agent_id to village

Revision ID: 3d5a9da45eb3
Revises: 7c35c242c594
Create Date: 2026-03-22 14:54:27.121884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5a9da45eb3'
down_revision: Union[str, Sequence[str], None] = '7c35c242c594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_role_key'), 'user', type_='unique')
    op.add_column('village', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_village_agent_id_user", 'village', 'user', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_village_agent_id_user", 'village', type_='foreignkey')
    op.drop_column('village', 'agent_id')
    op.create_unique_constraint(op.f('user_role_key'), 'user', ['role'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
