"""Align DB with domain models

Revision ID: 651144c1e5bb
Revises: 7cac0aa5451b
Create Date: 2025-12-17 14:33:29.819117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651144c1e5bb'
down_revision: Union[str, Sequence[str], None] = '7cac0aa5451b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bill_bill_code'), 'bill', ['bill_code'],
                    unique=True)
    op.create_index(op.f('ix_bill_customer_id'), 'bill', ['customer_id'],
                    unique=False)
    op.create_index(op.f('ix_bill_package_id'), 'bill', ['package_id'],
                    unique=False)
    op.add_column('customer', sa.Column('ftth64_id', sa.Integer(),
                                        nullable=False))

    op.create_index(op.f('ix_customer_customer_type_id'), 'customer', ['customer_type_id'], unique=False)
    op.create_index(op.f('ix_customer_ftth64_id'), 'customer', ['ftth64_id'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)

    op.create_index(op.f('ix_customer_village_id'), 'customer', ['village_id'], unique=False)
    op.create_foreign_key(None, 'customer', 'ftth64', ['ftth64_id'], ['id'])
    op.alter_column('customertype', 'name',
                    existing_type=postgresql.ENUM('REGULAR', 'SPONSORED', name='customertypeenum'),
                    nullable=False)
    op.create_index(op.f('ix_deviceinfo_account_number'), 'deviceinfo', ['account_number'], unique=True)
    op.create_index(op.f('ix_deviceinfo_customer_id'), 'deviceinfo', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_status_id'), 'deviceinfo', ['status_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_stb_id'), 'deviceinfo', ['stb_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_tvtype_id'), 'deviceinfo', ['tvtype_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_vc_number'), 'deviceinfo', ['vc_number'], unique=True)
    op.drop_constraint(op.f('deviceinfo_ftth64_id_fkey'), 'deviceinfo', type_='foreignkey')
    op.drop_column('deviceinfo', 'ftth64_id')
    op.create_index(op.f('ix_ftth64_code'), 'ftth64', ['code'], unique=False)
    op.create_index(op.f('ix_ftth64_name'), 'ftth64', ['name'], unique=False)
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=True)
    op.alter_column('status', 'name',
                    existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', name='statusenum'),
                    nullable=False)
    op.create_index(op.f('ix_subscription_customer_id'), 'subscription', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_package_id'), 'subscription', ['package_id'], unique=False)
    op.create_index(op.f('ix_tvtype_name'), 'tvtype', ['name'], unique=False)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)

    op.add_column('village', sa.Column('village_code', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_village_village_code'), 'village', ['village_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_village_village_code'), table_name='village')
    op.drop_column('village', 'village_code')
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('true'),
                    existing_nullable=False)
    op.drop_index(op.f('ix_tvtype_name'), table_name='tvtype')
    op.drop_index(op.f('ix_subscription_package_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_customer_id'), table_name='subscription')
    op.alter_column('status', 'name',
                    existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', name='statusenum'),
                    nullable=True)
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=False)
    op.drop_index(op.f('ix_ftth64_name'), table_name='ftth64')
    op.drop_index(op.f('ix_ftth64_code'), table_name='ftth64')
    op.add_column('deviceinfo', sa.Column('ftth64_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('deviceinfo_ftth64_id_fkey'), 'deviceinfo', 'ftth64', ['ftth64_id'], ['id'])
    op.drop_index(op.f('ix_deviceinfo_vc_number'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_tvtype_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_stb_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_status_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_customer_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_account_number'), table_name='deviceinfo')
    op.alter_column('customertype', 'name',
                    existing_type=postgresql.ENUM('REGULAR', 'SPONSORED', name='customertypeenum'),
                    nullable=True)
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_village_id'), table_name='customer')

    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_ftth64_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_type_id'), table_name='customer')

    op.drop_column('customer', 'ftth64_id')
    op.drop_index(op.f('ix_bill_package_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_customer_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_bill_code'), table_name='bill')
    # ### end Alembic commands ###
