"""Customer ftth64_code and schema alignment

Revision ID: 7c35c242c594
Revises: 571b19c0a67a
Create Date: 2026-01-29 15:06:49.423041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel   


# revision identifiers, used by Alembic.
revision: str = '7c35c242c594'
down_revision: Union[str, Sequence[str], None] = '571b19c0a67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('ftth64_code',
                                        sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_customer_ftth64_code'), 'customer',
                    ['ftth64_code'],
                    unique=True)
    op.drop_index(op.f('ix_ftth64_code'), table_name='ftth64')
    op.drop_column('ftth64', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ftth64', sa.Column('code', sa.VARCHAR(),
                                      autoincrement=False, nullable=False))
    op.create_index(op.f('ix_ftth64_code'), 'ftth64', ['code'], unique=False)
    op.drop_index(op.f('ix_customer_ftth64_code'), table_name='customer')
    op.drop_column('customer', 'ftth64_code')
    # ### end Alembic commands ###
