"""Set user.is_active default to true

Revision ID: 7cac0aa5451b
Revises: 0515a331f4f4
Create Date: 2025-12-14 23:59:27.046299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cac0aa5451b'
down_revision: Union[str, Sequence[str], None] = '0515a331f4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_active",
        server_default=sa.text("true"),
        existing_nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_active",
        server_default=sa.text("false"),
        existing_nullable=False
    )
    # ### end Alembic commands ###
