"""optimize indexes

Revision ID: 8c9c01036deb
Revises: fa256e6fe625
Create Date: 2026-04-19 13:24:04.524642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9c01036deb'
down_revision: Union[str, Sequence[str], None] = 'fa256e6fe625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bill_customer_latest', 'bill', ['customer_id', 'id'], unique=False)
    op.create_index(op.f('ix_bill_bill_date'), 'bill', ['bill_date'], unique=False)
    op.create_unique_constraint("uq_bill_bill_code", 'bill', ['bill_code'])
    op.drop_index(op.f('ix_bill_bill_code'), table_name='bill')
    op.create_unique_constraint("uq_customer_phone", 'customer', ['phone'])
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.create_unique_constraint("uq_customer_ftth8_code", 'customer', ['ftth8_code'])
    op.drop_index(op.f('ix_customer_ftth8_code'), table_name='customer')
    op.create_unique_constraint("uq_deviceinfo_account_number", 'deviceinfo', ['account_number'])
    op.create_unique_constraint("uq_deviceinfo_vc_number", 'deviceinfo', ['vc_number'])
    op.drop_index(op.f('ix_deviceinfo_account_number'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_customer_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_vc_number'), table_name='deviceinfo')
    op.create_unique_constraint("uq_user_user_code", 'user', ['user_code'])
    op.drop_index(op.f('ix_user_user_code'), table_name='user')
    op.create_index(op.f('ix_village_agent_id'), 'village', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_village_agent_id'), table_name='village')
    op.drop_constraint("uq_user_user_code", 'user', type_='unique')
    op.create_index(op.f('ix_user_user_code'), 'user', ['user_code'], unique=True)
    op.drop_constraint("uq_deviceinfo_account_number", 'deviceinfo', type_='unique')
    op.drop_constraint("uq_deviceinfo_vc_number", 'deviceinfo', type_='unique')
    op.create_index(op.f('ix_deviceinfo_vc_number'), 'deviceinfo', ['vc_number'], unique=True)
    op.create_index(op.f('ix_deviceinfo_customer_id'), 'deviceinfo', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_account_number'), 'deviceinfo', ['account_number'], unique=True)
    op.drop_constraint("uq_customer_phone", 'customer', type_='unique')
    op.drop_constraint("uq_customer_ftth8_code", 'customer', type_='unique')
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_index(op.f('ix_customer_ftth8_code'), 'customer', ['ftth8_code'], unique=True)
    op.drop_constraint("uq_bill_bill_code", 'bill', type_='unique')
    op.drop_index(op.f('ix_bill_bill_date'), table_name='bill')
    op.drop_index('idx_bill_customer_latest', table_name='bill')
    op.create_index(op.f('ix_bill_bill_code'), 'bill', ['bill_code'], unique=True)
    # ### end Alembic commands ###
