"""add created_by_id and change bill_amount to numeric

Revision ID: 8ec9f3b0e73c
Revises: d7313e729997
Create Date: 2025-12-22 20:55:02.281626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec9f3b0e73c'
down_revision: Union[str, Sequence[str], None] = 'd7313e729997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column(
        'bill',
        sa.Column('created_by_id', sa.Integer(), nullable=True)
    )

    # 2. Backfill existing rows (IMPORTANT)
    # Choose a valid user id (usually admin id = 1)
    op.execute(
        "UPDATE bill SET created_by_id = 1 WHERE created_by_id IS NULL"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        'bill',
        'created_by_id',
        nullable=False
    )

    # 4. Alter bill_amount type
    op.alter_column(
        'bill',
        'bill_amount',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False
    )

    # 5. Index + FK
    op.create_index(
        op.f('ix_bill_created_by_id'),
        'bill',
        ['created_by_id'],
        unique=False
    )
    op.create_foreign_key(
        'fk_bill_created_by_id_user',
        'bill',
        'user',
        ['created_by_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bill_created_by_id_user', 'bill', type_='foreignkey')
    op.drop_index(op.f('ix_bill_created_by_id'), table_name='bill')

    op.alter_column(
        'bill',
        'bill_amount',
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )

    op.drop_column('bill', 'created_by_id')
    # ### end Alembic commands ###
