"""add phone length constraint

Revision ID: 97d11a5519ad
Revises: 8c9c01036deb
Create Date: 2026-04-26 12:09:14.144040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d11a5519ad'
down_revision: Union[str, Sequence[str], None] = '8c9c01036deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

     # --- fail-fast data validation ---

    result = op.get_bind().execute(
        sa.text(
            'SELECT 1 FROM "user" WHERE LENGTH(phone) != 10 LIMIT 1;'
        )
    ).first()

    if result:
        raise Exception(
            "Migration aborted: found phone values not equal to 10 digits. Clean data before applying constraint."
        )

    # --- apply constraint ---
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
