"""initial

Revision ID: ba337749c57e
Revises: 
Create Date: 2026-04-05 14:53:53.927763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba337749c57e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customertype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('name', sa.Enum('regular', 'sponsored', name='customertypeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ftth64',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ftth64_name'), 'ftth64', ['name'], unique=False)
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=True)
    op.create_index(op.f('ix_package_price'), 'package', ['price'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('active', 'inactive', 'archived', name='statusenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tvtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tvtype_name'), 'tvtype', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', 'test_user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_code', sa.String(length=3), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_user_user_code'), 'user', ['user_code'], unique=True)
    op.create_table('village',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=6), nullable=False),
    sa.Column('village_code', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_village_name'), 'village', ['name'], unique=True)
    op.create_index(op.f('ix_village_postal_code'), 'village', ['postal_code'], unique=False)
    op.create_index(op.f('ix_village_village_code'), 'village', ['village_code'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_number', sa.String(), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('customer_type_id', sa.Integer(), nullable=False),
    sa.Column('ftth8_code', sa.String(length=100), nullable=True),
    sa.Column('ftth64_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_type_id'], ['customertype.id'], ),
    sa.ForeignKeyConstraint(['ftth64_id'], ['ftth64.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_customer_customer_type_id'), 'customer', ['customer_type_id'], unique=False)
    op.create_index(op.f('ix_customer_ftth64_id'), 'customer', ['ftth64_id'], unique=False)
    op.create_index(op.f('ix_customer_ftth8_code'), 'customer', ['ftth8_code'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_package_id'), 'customer', ['package_id'], unique=False)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_index(op.f('ix_customer_village_id'), 'customer', ['village_id'], unique=False)
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bill_code', sa.String(length=100), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('monthly_count', sa.Integer(), nullable=False),
    sa.Column('bill_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_bill_bill_code'), 'bill', ['bill_code'], unique=True)
    op.create_index(op.f('ix_bill_created_by_id'), 'bill', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_bill_customer_id'), 'bill', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bill_package_id'), 'bill', ['package_id'], unique=False)
    op.create_table('deviceinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('stb_id', sa.String(), nullable=True),
    sa.Column('vc_number', sa.String(length=100), nullable=False),
    sa.Column('previous_vc_number', sa.String(length=100), nullable=True),
    sa.Column('tv_name', sa.String(length=100), nullable=True),
    sa.Column('tvtype_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['tvtype_id'], ['tvtype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_deviceinfo_account_number'), 'deviceinfo', ['account_number'], unique=True)
    op.create_index(op.f('ix_deviceinfo_customer_id'), 'deviceinfo', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_status_id'), 'deviceinfo', ['status_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_stb_id'), 'deviceinfo', ['stb_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_tvtype_id'), 'deviceinfo', ['tvtype_id'], unique=False)
    op.create_index(op.f('ix_deviceinfo_vc_number'), 'deviceinfo', ['vc_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deviceinfo_vc_number'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_tvtype_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_stb_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_status_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_customer_id'), table_name='deviceinfo')
    op.drop_index(op.f('ix_deviceinfo_account_number'), table_name='deviceinfo')
    op.drop_table('deviceinfo')
    op.drop_index(op.f('ix_bill_package_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_customer_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_created_by_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_bill_code'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_customer_village_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_package_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_ftth8_code'), table_name='customer')
    op.drop_index(op.f('ix_customer_ftth64_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_type_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_village_village_code'), table_name='village')
    op.drop_index(op.f('ix_village_postal_code'), table_name='village')
    op.drop_index(op.f('ix_village_name'), table_name='village')
    op.drop_table('village')
    op.drop_index(op.f('ix_user_user_code'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tvtype_name'), table_name='tvtype')
    op.drop_table('tvtype')
    op.drop_table('status')
    op.drop_index(op.f('ix_package_price'), table_name='package')
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_ftth64_name'), table_name='ftth64')
    op.drop_table('ftth64')
    op.drop_table('customertype')
    # ### end Alembic commands ###
