"""Add unique constraint to village name

Revision ID: e62b15b3415e
Revises: 651144c1e5bb
Create Date: 2025-12-19 14:05:26.740541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e62b15b3415e'
down_revision: Union[str, Sequence[str], None] = '651144c1e5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_unique_constraint("uq_user_name", 'user', ['name'])

    op.drop_index(op.f('ix_village_name'), table_name='village')
    op.create_index(op.f('ix_village_name'), 'village', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_village_name'), table_name='village')
    op.create_index(op.f('ix_village_name'), 'village', ['name'], unique=False)

    op.drop_constraint("uq_user_name", 'user', type_='unique')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)

    # ### end Alembic commands ###
