"""add unique constraint to device.customer_id

Revision ID: fa256e6fe625
Revises: ba337749c57e
Create Date: 2026-04-07 14:39:13.979844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa256e6fe625'
down_revision: Union[str, Sequence[str], None] = 'ba337749c57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
            "uq_device_customer",
            "deviceinfo",
            ["customer_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_device_customer",
        "deviceinfo",
        type_="unique"
    )
    # ### end Alembic commands ###
