"""Align customer onboarding and village flags

Revision ID: fb933c0c9cfe
Revises: c54bd50ff440
Create Date: 2025-12-25 16:16:08.635621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb933c0c9cfe'
down_revision: Union[str, Sequence[str], None] = 'c54bd50ff440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # CUSTOMER → package_id
    # Selected during onboarding, allowed to be NULL initially
    op.add_column(
        'customer',
        sa.Column('package_id', sa.Integer(), nullable=True)
    )

    op.create_index(
        op.f('ix_customer_package_id'),
        'customer',
        ['package_id'],
        unique=False
    )

    op.create_foreign_key(
        'fk_customer_package_id',
        'customer',
        'package',
        ['package_id'],
        ['id']
    )

    # normalize phone uniqueness
    op.drop_constraint(
        op.f('customer_phone_key'),
        'customer',
        type_='unique'
    )
    op.create_index(
        op.f('ix_customer_phone'),
        'customer',
        ['phone'],
        unique=True
    )

    # DEVICEINFO → tv_name
    op.add_column(
        'deviceinfo',
        sa.Column('tv_name', sa.String(length=50), nullable=True)
    )

    # PACKAGE → enrichment
    op.add_column(
        'package',
        sa.Column('channel_count', sa.Integer(), nullable=True)
    )
    op.add_column(
        'package',
        sa.Column('features', sa.String(), nullable=True)
    )

    # VILLAGE → agent_restricted
    # Restricted by default
    op.add_column(
        'village',
        sa.Column(
            'agent_restricted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )

    # remove default after existing rows are populated
    op.alter_column(
        'village',
        'agent_restricted',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('village', 'agent_restricted')
    op.drop_column('package', 'features')
    op.drop_column('package', 'channel_count')
    op.drop_column('deviceinfo', 'tv_name')
    op.drop_constraint('fk_customer_package_id', 'customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_package_id'), table_name='customer')
    op.create_unique_constraint(op.f('customer_phone_key'), 'customer', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('customer', 'package_id')
    # ### end Alembic commands ###
